### ISSUE TITLE
Idp Initiated SSO

### ISSUE THREAD

**Issue by mkgn** [mrtristan/CoreSaml2Utils#5]
This is not really a bug, but a question I would like to get your input. I had a look at the original repo and your updated code. I am in need of Idp Initiated method of SSO. In that case, the client will not be re-directed to IdP login page. Basically the IdP will have a link to my application somewhere in their (say sharepoint site). So when their user clicks on that link, it'll redirect the user to my application with a SAMLResponce which I should decrypt (using their public key) and do the rest.

I guess your code is doing just that is it?

**Comment by mrtristan** [comment]
@mkgn  sorry, missed the notification here. i use this code for both idp initiated as well as sp initiated. it "just works." the poke from idp is essentially the same referral as if you had started the process so it doesn't really make a difference (if you implement it that way i suppose).
